### ISSUE TITLE
Incorrect comments

### ISSUE THREAD

**Issue by jamesarosen** [mashuDuek/vscode-jbuilder-extension#1]
The [language-configuration](https://github.com/mashuDuek/vscode-jbuilder-extension/blob/master/language-configuration.json) specifies
```js
"comments": {
  // symbol used for single line comment. Remove this entry if your language does not support line comments
  "lineComment": "//",
  // symbols used for start and end a block comment. Remove this entry if your language does not support block comments
  "blockComment": [ "/*", "*/" ]
},
```
but comments in JBuilder are the same as for Ruby:
```js
"comments": {
  "lineComment": "#",
  "blockComment": ["=begin", "=end"]
},
```

**Comment by mashuDuek** [comment]
Hey jamesarosen, apologies for my tardiness here! Thank you for pointing this out! 
Updated [here](https://github.com/mashuDuek/vscode-jbuilder-extension/commit/ee202f2815a802501150c28b9bafd6aac3cdcd98)
