### ISSUE TITLE
Odd repository link

### ISSUE THREAD

**Issue by jamesarosen** [mashuDuek/vscode-jbuilder-extension#2]
The `repository` value in [package.json](https://github.com/mashuDuek/vscode-jbuilder-extension/blob/master/package.json#L14) is
```
https://mashuduek@github.com/mashuDuek/vscode-jbuilder-extension
```

That causes this oddity when clicking the "Repository" link in VS Code or from NPM:

![Confirm login](https://user-images.githubusercontent.com/2406/103713404-18266400-4f71-11eb-9139-ee8e7aed0cdd.png)

It doesn't break anything, but I recommend removing the `mashuduek@` part at the beginning.

**Comment by mashuDuek** [comment]
Once again, apologies for the delay in the answer, and thanks a ton for helping :). 🙌 
Updated [here](https://github.com/mashuDuek/vscode-jbuilder-extension/commit/522d54312bc8935afcd541fc98a3c005d64cc8f3)
